import type { Metadata } from "next";
import { Inter, K2D } from "next/font/google";
import "./globals.css";
import { UsernameProvider } from "@/context/User/usernameProvider";
import { ToastContainer } from "react-toastify";
import { Toaster } from "react-hot-toast";

const k2d = K2D({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-k2d",
});

export const metadata: Metadata = {
  title: "Webchat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={`${k2d.variable} font-sans`}>
        <UsernameProvider>{children}</UsernameProvider>
      </body>
    </html>
  );
}
